export const CLICKED_BUTTON_REQUEST = 'BOTAO_CLICADO_REQUISIÇÃO';
export const CLICKED_BUTTON_SUCCESS = 'BOTAO_CLICADO_SUCESSO';
export const CLICKED_BUTTON_ERROR = 'BOTAO_CLICADO_ERRO';

export const LOGIN_REQUEST = 'LOGIN_REQUISIÇÃO';
export const LOGIN_SUCCESS = 'LOGIN_SUCESSO';
export const LOGIN_ERROR = 'LOGIN_ERRO';

export const REGISTER_REQUEST = 'REGISTER_REQUISIÇÃO';
export const REGISTER_CREATION_SUCCESS = 'REGISTER_CRIACAO_SUCESSO';
export const REGISTER_UPDATE_SUCCESS = 'REGISTER_ATUALIZACAO_SUCESSO';
export const REGISTER_ERROR = 'REGISTER_ERRO';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
